const translations={
 en:{
  meta:{title:'West Coast Immigration Law | Clear Immigration Guidance',description:'Immigration guidance for employment, family, humanitarian, citizenship and investment pathways. Start with a confidential case review.'},
  a11y:{skip:'Skip to content'},nav:{pathways:'Pathways',approach:'Approach',process:'Process',cta:'Review my options',menu:'Open menu'},
  hero:{eyebrow:'U.S. immigration, made clearer',title:'Your next chapter<br>deserves a <em>clear path.</em>',lead:'Tell us where you are now and where you want to go. We’ll help you understand the immigration pathways that may fit your goals—and what the next step could look like.',primary:'Explore my options',secondary:'See immigration pathways',note1:'Confidential inquiry',note2:'English & Russian',note3:'Nationwide matters',cardLabel:'Start with your goal',cardTitle:'Work. Family. Safety. A future.',card2Label:'First step',card2Title:'A focused case review',caption:'CALIFORNIA • UNITED STATES'},
  proof:{one:'Your circumstances come first',two:'Options explained in plain language',three:'A documented plan for next steps',four:'No outcome is promised or invented'},
  pathways:{eyebrow:'Find your starting point',title:'Immigration isn’t one road.<br><em>Let’s find yours.</em>',lead:'Every category has different eligibility rules, evidence and timing. Choose the outcome closest to your goal to begin a more focused conversation.',workTag:'Build your career',work:'Work & talent pathways',workDesc:'Explore H-1B, L-1, O-1, EB-1 and EB-2 NIW considerations based on your role, record and goals.',familyTag:'Bring loved ones closer',family:'Family immigration',familyDesc:'Marriage, fiancé(e), parent and family petitions—organized around the relationship and process involved.',humanTag:'Seek protection',human:'Humanitarian options',humanDesc:'A careful review of asylum and other potential humanitarian relief.',futureTag:'Make it permanent',future:'Green cards & citizenship',futureDesc:'Permanent residence, adjustment of status and naturalization process guidance.',discuss:'Discuss this pathway'},
  approach:{eyebrow:'The right kind of clarity',title:'Less legal fog.<br><em>More informed decisions.</em>',lead:'A strong immigration strategy starts by separating what is known, what needs evidence and what still needs legal analysis.',cta:'Start a focused review',p1:'We begin with the facts',p1d:'Your status, history, timing, family and professional record shape which questions matter first.',p2:'We explain trade-offs',p2d:'Different pathways can involve different evidence, uncertainty and sequencing. You should understand those differences.',p3:'We define the next action',p3d:'You leave the review knowing which information to gather and what decision comes next.'},
  process:{eyebrow:'A calm, structured process',title:'From uncertainty to<br><em>a workable next step.</em>',s1:'Share your situation',s1d:'Send a concise, confidential overview of your goal, current status and timing.',s2:'Identify the questions',s2d:'The review focuses on eligibility signals, missing facts and potential complications.',s3:'Compare pathways',s3d:'Understand which options may warrant deeper analysis and what each would require.',s4:'Plan the next move',s4d:'Receive a clear direction for documents, consultation or further legal work.'},
  contact:{eyebrow:'Your story starts the review',title:'Tell us where you are.<br><em>We’ll help clarify what’s next.</em>',lead:'Complete the short intake below. The form prepares an email in your device so you can review the details before sending.',point1:'No automated approval promises',point2:'No attorney-client relationship until a written agreement',point3:'Avoid including highly sensitive IDs in this first message',formTag:'Confidential inquiry',formTitle:'Request a case review',name:'Your name',namePh:'Full name',email:'Email',topic:'What would you like to explore?',choose:'Choose a pathway',employment:'Work & talent',family:'Family immigration',humanitarian:'Humanitarian options',permanent:'Green card or citizenship',other:'Not sure / other',message:'Briefly describe your goal and current situation',messagePh:'What outcome are you seeking? What is your current status? Is there a deadline?',consent:'I understand this inquiry does not create an attorney-client relationship and I should not include highly sensitive identifiers.',submit:'Prepare my inquiry',note:'This button opens your email app. Nothing is silently submitted.',required:'Please complete this field.',emailInvalid:'Enter a valid email address.',consentError:'Please acknowledge this notice.',ready:'Your email app is opening. Review the message before sending.',subject:'Immigration case review inquiry'},
  footer:{line:'Clearer questions. Better-informed immigration decisions.',disclaimer:'General information only—not legal advice. Results depend on individual facts and applicable law. No outcome is guaranteed.'}
 },
 ru:{
  meta:{title:'West Coast Immigration Law | Понятный путь в иммиграции США',description:'Иммиграционные направления для работы, семьи, гуманитарной защиты, Green Card и гражданства. Начните с конфиденциального разбора ситуации.'},
  a11y:{skip:'Перейти к содержанию'},nav:{pathways:'Направления',approach:'Наш подход',process:'Процесс',cta:'Разобрать варианты',menu:'Открыть меню'},
  hero:{eyebrow:'Иммиграция в США — понятнее',title:'Новая глава вашей жизни<br>заслуживает <em>ясного пути.</em>',lead:'Расскажите, где вы сейчас и к чему стремитесь. Мы поможем понять, какие иммиграционные направления стоит рассмотреть и каким может быть следующий шаг.',primary:'Разобрать мои варианты',secondary:'Смотреть направления',note1:'Конфиденциальный запрос',note2:'Русский и английский',note3:'Дела по всей территории США',cardLabel:'Начинаем с вашей цели',cardTitle:'Работа. Семья. Безопасность. Будущее.',card2Label:'Первый шаг',card2Title:'Предметный разбор ситуации',caption:'КАЛИФОРНИЯ • СОЕДИНЁННЫЕ ШТАТЫ'},
  proof:{one:'В центре — ваши обстоятельства',two:'Варианты простым языком',three:'Понятный план следующих шагов',four:'Никаких выдуманных гарантий результата'},
  pathways:{eyebrow:'Найдите отправную точку',title:'Иммиграция — не одна дорога.<br><em>Найдём вашу.</em>',lead:'У каждой категории свои требования, доказательства и сроки. Выберите цель, которая ближе всего к вашей ситуации, чтобы начать предметный разговор.',workTag:'Развивайте карьеру',work:'Работа и талант',workDesc:'Рассмотрим вопросы H-1B, L-1, O-1, EB-1 и EB-2 NIW с учётом вашей роли, достижений и целей.',familyTag:'Будьте ближе к родным',family:'Семейная иммиграция',familyDesc:'Брак, виза жениха или невесты, петиции для родителей и других родственников — с учётом конкретных отношений и процесса.',humanTag:'Ищите защиту',human:'Гуманитарные варианты',humanDesc:'Внимательный анализ убежища и других возможных форм гуманитарной защиты.',futureTag:'Закрепите будущее',future:'Green Card и гражданство',futureDesc:'Постоянное резидентство, изменение статуса и процесс натурализации.',discuss:'Обсудить направление'},
  approach:{eyebrow:'Ясность, которая помогает',title:'Меньше юридического тумана.<br><em>Больше осознанных решений.</em>',lead:'Сильная иммиграционная стратегия начинается с разделения фактов, необходимых доказательств и вопросов, которым ещё нужен юридический анализ.',cta:'Начать разбор',p1:'Сначала — факты',p1d:'Ваш статус, история, сроки, семья и профессиональный опыт определяют, какие вопросы важнее всего.',p2:'Объясняем компромиссы',p2d:'Разные пути требуют разных доказательств, сроков и последовательности. Вы должны понимать эти различия.',p3:'Определяем следующее действие',p3d:'После разбора вы понимаете, какую информацию собирать и какое решение принимать дальше.'},
  process:{eyebrow:'Спокойный и структурный процесс',title:'От неопределённости<br><em>к рабочему следующему шагу.</em>',s1:'Опишите ситуацию',s1d:'Кратко и конфиденциально расскажите о цели, текущем статусе и сроках.',s2:'Определим вопросы',s2d:'Разбор сфокусирован на признаках соответствия, недостающих фактах и возможных сложностях.',s3:'Сравним направления',s3d:'Поймите, какие варианты требуют более глубокого анализа и что понадобится для каждого.',s4:'Спланируем следующий шаг',s4d:'Получите ясное направление по документам, консультации или дальнейшей юридической работе.'},
  contact:{eyebrow:'Разбор начинается с вашей истории',title:'Расскажите, где вы сейчас.<br><em>Мы поможем прояснить, что дальше.</em>',lead:'Заполните короткую форму. Она подготовит письмо в вашем почтовом приложении, чтобы вы проверили информацию перед отправкой.',point1:'Никаких автоматических обещаний одобрения',point2:'Отношения адвокат–клиент возникают только после письменного соглашения',point3:'Не указывайте особо чувствительные номера документов в первом сообщении',formTag:'Конфиденциальный запрос',formTitle:'Запросить разбор ситуации',name:'Ваше имя',namePh:'Имя и фамилия',email:'Email',topic:'Что вы хотите рассмотреть?',choose:'Выберите направление',employment:'Работа и талант',family:'Семейная иммиграция',humanitarian:'Гуманитарные варианты',permanent:'Green Card или гражданство',other:'Не уверен(а) / другое',message:'Кратко опишите цель и текущую ситуацию',messagePh:'К какому результату вы стремитесь? Какой у вас статус? Есть ли срочный срок?',consent:'Я понимаю, что этот запрос не создаёт отношений адвокат–клиент, и не буду указывать особо чувствительные идентификаторы.',submit:'Подготовить запрос',note:'Кнопка откроет ваше почтовое приложение. Ничего не отправляется скрытно.',required:'Заполните это поле.',emailInvalid:'Введите корректный email.',consentError:'Подтвердите ознакомление с уведомлением.',ready:'Открываем почтовое приложение. Проверьте письмо перед отправкой.',subject:'Запрос на разбор иммиграционной ситуации'},
  footer:{line:'Более ясные вопросы. Более осознанные иммиграционные решения.',disclaimer:'Только общая информация — не юридическая консультация. Результат зависит от конкретных фактов и применимого права. Исход не гарантируется.'}
 }
};
let currentLang=/^\/ru(\/|$)/.test(location.pathname)?'ru':'en';
function value(key){return key.split('.').reduce((v,k)=>v&&v[k],translations[currentLang])??key}
function applyTranslations(){document.documentElement.lang=currentLang;document.title=value('meta.title');const md=document.querySelector('meta[name="description"]');if(md)md.content=value('meta.description');document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=value(el.dataset.i18n));document.querySelectorAll('[data-i18n-html]').forEach(el=>el.innerHTML=value(el.dataset.i18nHtml));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=value(el.dataset.i18nPlaceholder));document.querySelectorAll('.lang-btn').forEach(el=>{const active=el.dataset.lang===currentLang;el.classList.toggle('active',active);el.setAttribute('aria-current',active?'page':'false')});const menu=document.getElementById('menuButton');if(menu)menu.setAttribute('aria-label',value('nav.menu'))}
window.i18n={t:value,getLanguage:()=>currentLang};applyTranslations();
